linters:
  enable:
    - gofmt
    - nolintlint

linters-settings:
  errcheck:
    exclude-functions:
      - (*github.com/spf13/cobra.Command).RegisterFlagCompletionFunc
      - (*github.com/spf13/cobra.Command).MarkFlagRequired
      - (*github.com/spf13/cobra.Command).Usage
      - (*github.com/spf13/pflag.FlagSet).MarkDeprecated
      - (*github.com/spf13/pflag.FlagSet).MarkHidden
issues:
  max-issues-per-linter: 0
  max-same-issues: 0