// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package api

import (
	"context"
	"encoding/json"

	"github.com/Khan/genqlient/graphql"
)

type ContainerJobCreateInput struct {
	Name      string             `json:"name"`
	Namespace string             `json:"namespace"`
	Resources ContainerResources `json:"resources"`
	Registry  *string            `json:"registry"`
	Image     string             `json:"image"`
	// Entrypoint of the container.
	// This field will overwrite the default entrypoint of the image. When the field is omitted, the default entrypoint of the image will be used.
	//
	// Null will reset the command to the default.
	//
	// Entry point is the first command executed when the container starts. It will receive the command as arguments.
	// For example when the entrypoint is `python`, the command `app.py` will be executed as `python app.py`.
	//
	// This field is defined in docker exec format. https://docs.docker.com/reference/dockerfile/#shell-and-exec-form
	Entrypoint []string `json:"entrypoint"`
	// Command to run.
	// This is the command executed at the given schedule.
	// When the field is omitted, the default command of the image will be used.
	//
	// Null will reset the command to the default.
	// The command will be passed to the entrypoint as arguments. Use quotes to pass an argument with spaces.
	//
	// Environment variables can be used in the command by using the syntax `$(ENVIRONMENT_VARIABLE)`.
	//
	// Example: `echo "Hello $(NAME)"`.
	//
	// This field is defined in docker exec format. https://docs.docker.com/reference/dockerfile/#shell-and-exec-form
	Command []string `json:"command"`
	// Enable or disable the job.
	// By disabling a job, it will not be executed, we do keep the configuration.
	Enabled bool `json:"enabled"`
	// Cron notation to schedule jobs.
	// Format is equal to regular cron notation.
	// For example, to run a job every day at 4am, use `0 4 * * *`.
	// You can use https://crontab.guru/ to help you build your cron expressions.
	Schedule string `json:"schedule"`
	// Environment variables to be set in the job.
	EnvironmentVariables []EnvironmentVariableInput `json:"environmentVariables"`
	Mounts               []MountInput               `json:"mounts"`
}

// GetName returns ContainerJobCreateInput.Name, and is useful for accessing the field via an interface.
func (v *ContainerJobCreateInput) GetName() string { return v.Name }

// GetNamespace returns ContainerJobCreateInput.Namespace, and is useful for accessing the field via an interface.
func (v *ContainerJobCreateInput) GetNamespace() string { return v.Namespace }

// GetResources returns ContainerJobCreateInput.Resources, and is useful for accessing the field via an interface.
func (v *ContainerJobCreateInput) GetResources() ContainerResources { return v.Resources }

// GetRegistry returns ContainerJobCreateInput.Registry, and is useful for accessing the field via an interface.
func (v *ContainerJobCreateInput) GetRegistry() *string { return v.Registry }

// GetImage returns ContainerJobCreateInput.Image, and is useful for accessing the field via an interface.
func (v *ContainerJobCreateInput) GetImage() string { return v.Image }

// GetEntrypoint returns ContainerJobCreateInput.Entrypoint, and is useful for accessing the field via an interface.
func (v *ContainerJobCreateInput) GetEntrypoint() []string { return v.Entrypoint }

// GetCommand returns ContainerJobCreateInput.Command, and is useful for accessing the field via an interface.
func (v *ContainerJobCreateInput) GetCommand() []string { return v.Command }

// GetEnabled returns ContainerJobCreateInput.Enabled, and is useful for accessing the field via an interface.
func (v *ContainerJobCreateInput) GetEnabled() bool { return v.Enabled }

// GetSchedule returns ContainerJobCreateInput.Schedule, and is useful for accessing the field via an interface.
func (v *ContainerJobCreateInput) GetSchedule() string { return v.Schedule }

// GetEnvironmentVariables returns ContainerJobCreateInput.EnvironmentVariables, and is useful for accessing the field via an interface.
func (v *ContainerJobCreateInput) GetEnvironmentVariables() []EnvironmentVariableInput {
	return v.EnvironmentVariables
}

// GetMounts returns ContainerJobCreateInput.Mounts, and is useful for accessing the field via an interface.
func (v *ContainerJobCreateInput) GetMounts() []MountInput { return v.Mounts }

type ContainerJobModifyInput struct {
	Name      string              `json:"name"`
	Namespace string              `json:"namespace"`
	Resources *ContainerResources `json:"resources"`
	Registry  *string             `json:"registry"`
	Image     *string             `json:"image"`
	// Entrypoint of the container.
	// This field will overwrite the default entrypoint of the image. When the field is omitted, the default entrypoint of the image will be used.
	//
	// Null will reset the command to the default.
	//
	// Entry point is the first command executed when the container starts. It will receive the command as arguments.
	// For example when the entrypoint is `python`, the command `app.py` will be executed as `python app.py`.
	//
	// This field is defined in docker exec format. https://docs.docker.com/reference/dockerfile/#shell-and-exec-form
	Entrypoint []string `json:"entrypoint"`
	// Command to run.
	// This is the command executed at the given schedule.
	// When the field is omitted, the default command of the image will be used.
	//
	// Null will reset the command to the default.
	// The command will be passed to the entrypoint as arguments. Use quotes to pass an argument with spaces.
	//
	// Environment variables can be used in the command by using the syntax `$(ENVIRONMENT_VARIABLE)`.
	//
	// Example: `echo "Hello $(NAME)"`.
	//
	// This field is defined in docker exec format. https://docs.docker.com/reference/dockerfile/#shell-and-exec-form
	Command []string `json:"command"`
	// Enable or disable the job.
	// By disabling a job, it will not be executed, we do keep the configuration.
	Enabled *bool `json:"enabled"`
	// Cron notation to schedule jobs.
	// Format is equal to regular cron notation.
	// For example, to run a job every day at 4am, use `0 4 * * *`.
	// You can use https://crontab.guru/ to help you build your cron expressions.
	Schedule *string `json:"schedule"`
	// Environment variables to be set in the job.
	EnvironmentVariables []EnvironmentVariableInput `json:"environmentVariables"`
	Mounts               []MountInput               `json:"mounts"`
}

// GetName returns ContainerJobModifyInput.Name, and is useful for accessing the field via an interface.
func (v *ContainerJobModifyInput) GetName() string { return v.Name }

// GetNamespace returns ContainerJobModifyInput.Namespace, and is useful for accessing the field via an interface.
func (v *ContainerJobModifyInput) GetNamespace() string { return v.Namespace }

// GetResources returns ContainerJobModifyInput.Resources, and is useful for accessing the field via an interface.
func (v *ContainerJobModifyInput) GetResources() *ContainerResources { return v.Resources }

// GetRegistry returns ContainerJobModifyInput.Registry, and is useful for accessing the field via an interface.
func (v *ContainerJobModifyInput) GetRegistry() *string { return v.Registry }

// GetImage returns ContainerJobModifyInput.Image, and is useful for accessing the field via an interface.
func (v *ContainerJobModifyInput) GetImage() *string { return v.Image }

// GetEntrypoint returns ContainerJobModifyInput.Entrypoint, and is useful for accessing the field via an interface.
func (v *ContainerJobModifyInput) GetEntrypoint() []string { return v.Entrypoint }

// GetCommand returns ContainerJobModifyInput.Command, and is useful for accessing the field via an interface.
func (v *ContainerJobModifyInput) GetCommand() []string { return v.Command }

// GetEnabled returns ContainerJobModifyInput.Enabled, and is useful for accessing the field via an interface.
func (v *ContainerJobModifyInput) GetEnabled() *bool { return v.Enabled }

// GetSchedule returns ContainerJobModifyInput.Schedule, and is useful for accessing the field via an interface.
func (v *ContainerJobModifyInput) GetSchedule() *string { return v.Schedule }

// GetEnvironmentVariables returns ContainerJobModifyInput.EnvironmentVariables, and is useful for accessing the field via an interface.
func (v *ContainerJobModifyInput) GetEnvironmentVariables() []EnvironmentVariableInput {
	return v.EnvironmentVariables
}

// GetMounts returns ContainerJobModifyInput.Mounts, and is useful for accessing the field via an interface.
func (v *ContainerJobModifyInput) GetMounts() []MountInput { return v.Mounts }

// ContainerJobResult includes the GraphQL fields of ContainerJob requested by the fragment ContainerJobResult.
type ContainerJobResult struct {
	Name    string `json:"name"`
	Image   string `json:"image"`
	Enabled bool   `json:"enabled"`
	State   string `json:"state"`
}

// GetName returns ContainerJobResult.Name, and is useful for accessing the field via an interface.
func (v *ContainerJobResult) GetName() string { return v.Name }

// GetImage returns ContainerJobResult.Image, and is useful for accessing the field via an interface.
func (v *ContainerJobResult) GetImage() string { return v.Image }

// GetEnabled returns ContainerJobResult.Enabled, and is useful for accessing the field via an interface.
func (v *ContainerJobResult) GetEnabled() bool { return v.Enabled }

// GetState returns ContainerJobResult.State, and is useful for accessing the field via an interface.
func (v *ContainerJobResult) GetState() string { return v.State }

type ContainerResources string

const (
	ContainerResourcesCpu250Ram500    ContainerResources = "CPU_250_RAM_500"
	ContainerResourcesCpu250Ram1000   ContainerResources = "CPU_250_RAM_1000"
	ContainerResourcesCpu250Ram2000   ContainerResources = "CPU_250_RAM_2000"
	ContainerResourcesCpu250Ram3000   ContainerResources = "CPU_250_RAM_3000"
	ContainerResourcesCpu250Ram4000   ContainerResources = "CPU_250_RAM_4000"
	ContainerResourcesCpu250Ram5000   ContainerResources = "CPU_250_RAM_5000"
	ContainerResourcesCpu250Ram6000   ContainerResources = "CPU_250_RAM_6000"
	ContainerResourcesCpu250Ram7000   ContainerResources = "CPU_250_RAM_7000"
	ContainerResourcesCpu250Ram8000   ContainerResources = "CPU_250_RAM_8000"
	ContainerResourcesCpu250Ram9000   ContainerResources = "CPU_250_RAM_9000"
	ContainerResourcesCpu250Ram10000  ContainerResources = "CPU_250_RAM_10000"
	ContainerResourcesCpu250Ram11000  ContainerResources = "CPU_250_RAM_11000"
	ContainerResourcesCpu250Ram12000  ContainerResources = "CPU_250_RAM_12000"
	ContainerResourcesCpu250Ram13000  ContainerResources = "CPU_250_RAM_13000"
	ContainerResourcesCpu250Ram14000  ContainerResources = "CPU_250_RAM_14000"
	ContainerResourcesCpu250Ram15000  ContainerResources = "CPU_250_RAM_15000"
	ContainerResourcesCpu250Ram16000  ContainerResources = "CPU_250_RAM_16000"
	ContainerResourcesCpu500Ram500    ContainerResources = "CPU_500_RAM_500"
	ContainerResourcesCpu500Ram1000   ContainerResources = "CPU_500_RAM_1000"
	ContainerResourcesCpu500Ram2000   ContainerResources = "CPU_500_RAM_2000"
	ContainerResourcesCpu500Ram3000   ContainerResources = "CPU_500_RAM_3000"
	ContainerResourcesCpu500Ram4000   ContainerResources = "CPU_500_RAM_4000"
	ContainerResourcesCpu500Ram5000   ContainerResources = "CPU_500_RAM_5000"
	ContainerResourcesCpu500Ram6000   ContainerResources = "CPU_500_RAM_6000"
	ContainerResourcesCpu500Ram7000   ContainerResources = "CPU_500_RAM_7000"
	ContainerResourcesCpu500Ram8000   ContainerResources = "CPU_500_RAM_8000"
	ContainerResourcesCpu500Ram9000   ContainerResources = "CPU_500_RAM_9000"
	ContainerResourcesCpu500Ram10000  ContainerResources = "CPU_500_RAM_10000"
	ContainerResourcesCpu500Ram11000  ContainerResources = "CPU_500_RAM_11000"
	ContainerResourcesCpu500Ram12000  ContainerResources = "CPU_500_RAM_12000"
	ContainerResourcesCpu500Ram13000  ContainerResources = "CPU_500_RAM_13000"
	ContainerResourcesCpu500Ram14000  ContainerResources = "CPU_500_RAM_14000"
	ContainerResourcesCpu500Ram15000  ContainerResources = "CPU_500_RAM_15000"
	ContainerResourcesCpu500Ram16000  ContainerResources = "CPU_500_RAM_16000"
	ContainerResourcesCpu750Ram500    ContainerResources = "CPU_750_RAM_500"
	ContainerResourcesCpu750Ram1000   ContainerResources = "CPU_750_RAM_1000"
	ContainerResourcesCpu750Ram2000   ContainerResources = "CPU_750_RAM_2000"
	ContainerResourcesCpu750Ram3000   ContainerResources = "CPU_750_RAM_3000"
	ContainerResourcesCpu750Ram4000   ContainerResources = "CPU_750_RAM_4000"
	ContainerResourcesCpu750Ram5000   ContainerResources = "CPU_750_RAM_5000"
	ContainerResourcesCpu750Ram6000   ContainerResources = "CPU_750_RAM_6000"
	ContainerResourcesCpu750Ram7000   ContainerResources = "CPU_750_RAM_7000"
	ContainerResourcesCpu750Ram8000   ContainerResources = "CPU_750_RAM_8000"
	ContainerResourcesCpu750Ram9000   ContainerResources = "CPU_750_RAM_9000"
	ContainerResourcesCpu750Ram10000  ContainerResources = "CPU_750_RAM_10000"
	ContainerResourcesCpu750Ram11000  ContainerResources = "CPU_750_RAM_11000"
	ContainerResourcesCpu750Ram12000  ContainerResources = "CPU_750_RAM_12000"
	ContainerResourcesCpu750Ram13000  ContainerResources = "CPU_750_RAM_13000"
	ContainerResourcesCpu750Ram14000  ContainerResources = "CPU_750_RAM_14000"
	ContainerResourcesCpu750Ram15000  ContainerResources = "CPU_750_RAM_15000"
	ContainerResourcesCpu750Ram16000  ContainerResources = "CPU_750_RAM_16000"
	ContainerResourcesCpu1000Ram500   ContainerResources = "CPU_1000_RAM_500"
	ContainerResourcesCpu1000Ram1000  ContainerResources = "CPU_1000_RAM_1000"
	ContainerResourcesCpu1000Ram2000  ContainerResources = "CPU_1000_RAM_2000"
	ContainerResourcesCpu1000Ram3000  ContainerResources = "CPU_1000_RAM_3000"
	ContainerResourcesCpu1000Ram4000  ContainerResources = "CPU_1000_RAM_4000"
	ContainerResourcesCpu1000Ram5000  ContainerResources = "CPU_1000_RAM_5000"
	ContainerResourcesCpu1000Ram6000  ContainerResources = "CPU_1000_RAM_6000"
	ContainerResourcesCpu1000Ram7000  ContainerResources = "CPU_1000_RAM_7000"
	ContainerResourcesCpu1000Ram8000  ContainerResources = "CPU_1000_RAM_8000"
	ContainerResourcesCpu1000Ram9000  ContainerResources = "CPU_1000_RAM_9000"
	ContainerResourcesCpu1000Ram10000 ContainerResources = "CPU_1000_RAM_10000"
	ContainerResourcesCpu1000Ram11000 ContainerResources = "CPU_1000_RAM_11000"
	ContainerResourcesCpu1000Ram12000 ContainerResources = "CPU_1000_RAM_12000"
	ContainerResourcesCpu1000Ram13000 ContainerResources = "CPU_1000_RAM_13000"
	ContainerResourcesCpu1000Ram14000 ContainerResources = "CPU_1000_RAM_14000"
	ContainerResourcesCpu1000Ram15000 ContainerResources = "CPU_1000_RAM_15000"
	ContainerResourcesCpu1000Ram16000 ContainerResources = "CPU_1000_RAM_16000"
	ContainerResourcesCpu2000Ram500   ContainerResources = "CPU_2000_RAM_500"
	ContainerResourcesCpu2000Ram1000  ContainerResources = "CPU_2000_RAM_1000"
	ContainerResourcesCpu2000Ram2000  ContainerResources = "CPU_2000_RAM_2000"
	ContainerResourcesCpu2000Ram3000  ContainerResources = "CPU_2000_RAM_3000"
	ContainerResourcesCpu2000Ram4000  ContainerResources = "CPU_2000_RAM_4000"
	ContainerResourcesCpu2000Ram5000  ContainerResources = "CPU_2000_RAM_5000"
	ContainerResourcesCpu2000Ram6000  ContainerResources = "CPU_2000_RAM_6000"
	ContainerResourcesCpu2000Ram7000  ContainerResources = "CPU_2000_RAM_7000"
	ContainerResourcesCpu2000Ram8000  ContainerResources = "CPU_2000_RAM_8000"
	ContainerResourcesCpu2000Ram9000  ContainerResources = "CPU_2000_RAM_9000"
	ContainerResourcesCpu2000Ram10000 ContainerResources = "CPU_2000_RAM_10000"
	ContainerResourcesCpu2000Ram11000 ContainerResources = "CPU_2000_RAM_11000"
	ContainerResourcesCpu2000Ram12000 ContainerResources = "CPU_2000_RAM_12000"
	ContainerResourcesCpu2000Ram13000 ContainerResources = "CPU_2000_RAM_13000"
	ContainerResourcesCpu2000Ram14000 ContainerResources = "CPU_2000_RAM_14000"
	ContainerResourcesCpu2000Ram15000 ContainerResources = "CPU_2000_RAM_15000"
	ContainerResourcesCpu2000Ram16000 ContainerResources = "CPU_2000_RAM_16000"
	ContainerResourcesCpu3000Ram500   ContainerResources = "CPU_3000_RAM_500"
	ContainerResourcesCpu3000Ram1000  ContainerResources = "CPU_3000_RAM_1000"
	ContainerResourcesCpu3000Ram2000  ContainerResources = "CPU_3000_RAM_2000"
	ContainerResourcesCpu3000Ram3000  ContainerResources = "CPU_3000_RAM_3000"
	ContainerResourcesCpu3000Ram4000  ContainerResources = "CPU_3000_RAM_4000"
	ContainerResourcesCpu3000Ram5000  ContainerResources = "CPU_3000_RAM_5000"
	ContainerResourcesCpu3000Ram6000  ContainerResources = "CPU_3000_RAM_6000"
	ContainerResourcesCpu3000Ram7000  ContainerResources = "CPU_3000_RAM_7000"
	ContainerResourcesCpu3000Ram8000  ContainerResources = "CPU_3000_RAM_8000"
	ContainerResourcesCpu3000Ram9000  ContainerResources = "CPU_3000_RAM_9000"
	ContainerResourcesCpu3000Ram10000 ContainerResources = "CPU_3000_RAM_10000"
	ContainerResourcesCpu3000Ram11000 ContainerResources = "CPU_3000_RAM_11000"
	ContainerResourcesCpu3000Ram12000 ContainerResources = "CPU_3000_RAM_12000"
	ContainerResourcesCpu3000Ram13000 ContainerResources = "CPU_3000_RAM_13000"
	ContainerResourcesCpu3000Ram14000 ContainerResources = "CPU_3000_RAM_14000"
	ContainerResourcesCpu3000Ram15000 ContainerResources = "CPU_3000_RAM_15000"
	ContainerResourcesCpu3000Ram16000 ContainerResources = "CPU_3000_RAM_16000"
	ContainerResourcesCpu4000Ram500   ContainerResources = "CPU_4000_RAM_500"
	ContainerResourcesCpu4000Ram1000  ContainerResources = "CPU_4000_RAM_1000"
	ContainerResourcesCpu4000Ram2000  ContainerResources = "CPU_4000_RAM_2000"
	ContainerResourcesCpu4000Ram3000  ContainerResources = "CPU_4000_RAM_3000"
	ContainerResourcesCpu4000Ram4000  ContainerResources = "CPU_4000_RAM_4000"
	ContainerResourcesCpu4000Ram5000  ContainerResources = "CPU_4000_RAM_5000"
	ContainerResourcesCpu4000Ram6000  ContainerResources = "CPU_4000_RAM_6000"
	ContainerResourcesCpu4000Ram7000  ContainerResources = "CPU_4000_RAM_7000"
	ContainerResourcesCpu4000Ram8000  ContainerResources = "CPU_4000_RAM_8000"
	ContainerResourcesCpu4000Ram9000  ContainerResources = "CPU_4000_RAM_9000"
	ContainerResourcesCpu4000Ram10000 ContainerResources = "CPU_4000_RAM_10000"
	ContainerResourcesCpu4000Ram11000 ContainerResources = "CPU_4000_RAM_11000"
	ContainerResourcesCpu4000Ram12000 ContainerResources = "CPU_4000_RAM_12000"
	ContainerResourcesCpu4000Ram13000 ContainerResources = "CPU_4000_RAM_13000"
	ContainerResourcesCpu4000Ram14000 ContainerResources = "CPU_4000_RAM_14000"
	ContainerResourcesCpu4000Ram15000 ContainerResources = "CPU_4000_RAM_15000"
	ContainerResourcesCpu4000Ram16000 ContainerResources = "CPU_4000_RAM_16000"
)

var AllContainerResources = []ContainerResources{
	ContainerResourcesCpu250Ram500,
	ContainerResourcesCpu250Ram1000,
	ContainerResourcesCpu250Ram2000,
	ContainerResourcesCpu250Ram3000,
	ContainerResourcesCpu250Ram4000,
	ContainerResourcesCpu250Ram5000,
	ContainerResourcesCpu250Ram6000,
	ContainerResourcesCpu250Ram7000,
	ContainerResourcesCpu250Ram8000,
	ContainerResourcesCpu250Ram9000,
	ContainerResourcesCpu250Ram10000,
	ContainerResourcesCpu250Ram11000,
	ContainerResourcesCpu250Ram12000,
	ContainerResourcesCpu250Ram13000,
	ContainerResourcesCpu250Ram14000,
	ContainerResourcesCpu250Ram15000,
	ContainerResourcesCpu250Ram16000,
	ContainerResourcesCpu500Ram500,
	ContainerResourcesCpu500Ram1000,
	ContainerResourcesCpu500Ram2000,
	ContainerResourcesCpu500Ram3000,
	ContainerResourcesCpu500Ram4000,
	ContainerResourcesCpu500Ram5000,
	ContainerResourcesCpu500Ram6000,
	ContainerResourcesCpu500Ram7000,
	ContainerResourcesCpu500Ram8000,
	ContainerResourcesCpu500Ram9000,
	ContainerResourcesCpu500Ram10000,
	ContainerResourcesCpu500Ram11000,
	ContainerResourcesCpu500Ram12000,
	ContainerResourcesCpu500Ram13000,
	ContainerResourcesCpu500Ram14000,
	ContainerResourcesCpu500Ram15000,
	ContainerResourcesCpu500Ram16000,
	ContainerResourcesCpu750Ram500,
	ContainerResourcesCpu750Ram1000,
	ContainerResourcesCpu750Ram2000,
	ContainerResourcesCpu750Ram3000,
	ContainerResourcesCpu750Ram4000,
	ContainerResourcesCpu750Ram5000,
	ContainerResourcesCpu750Ram6000,
	ContainerResourcesCpu750Ram7000,
	ContainerResourcesCpu750Ram8000,
	ContainerResourcesCpu750Ram9000,
	ContainerResourcesCpu750Ram10000,
	ContainerResourcesCpu750Ram11000,
	ContainerResourcesCpu750Ram12000,
	ContainerResourcesCpu750Ram13000,
	ContainerResourcesCpu750Ram14000,
	ContainerResourcesCpu750Ram15000,
	ContainerResourcesCpu750Ram16000,
	ContainerResourcesCpu1000Ram500,
	ContainerResourcesCpu1000Ram1000,
	ContainerResourcesCpu1000Ram2000,
	ContainerResourcesCpu1000Ram3000,
	ContainerResourcesCpu1000Ram4000,
	ContainerResourcesCpu1000Ram5000,
	ContainerResourcesCpu1000Ram6000,
	ContainerResourcesCpu1000Ram7000,
	ContainerResourcesCpu1000Ram8000,
	ContainerResourcesCpu1000Ram9000,
	ContainerResourcesCpu1000Ram10000,
	ContainerResourcesCpu1000Ram11000,
	ContainerResourcesCpu1000Ram12000,
	ContainerResourcesCpu1000Ram13000,
	ContainerResourcesCpu1000Ram14000,
	ContainerResourcesCpu1000Ram15000,
	ContainerResourcesCpu1000Ram16000,
	ContainerResourcesCpu2000Ram500,
	ContainerResourcesCpu2000Ram1000,
	ContainerResourcesCpu2000Ram2000,
	ContainerResourcesCpu2000Ram3000,
	ContainerResourcesCpu2000Ram4000,
	ContainerResourcesCpu2000Ram5000,
	ContainerResourcesCpu2000Ram6000,
	ContainerResourcesCpu2000Ram7000,
	ContainerResourcesCpu2000Ram8000,
	ContainerResourcesCpu2000Ram9000,
	ContainerResourcesCpu2000Ram10000,
	ContainerResourcesCpu2000Ram11000,
	ContainerResourcesCpu2000Ram12000,
	ContainerResourcesCpu2000Ram13000,
	ContainerResourcesCpu2000Ram14000,
	ContainerResourcesCpu2000Ram15000,
	ContainerResourcesCpu2000Ram16000,
	ContainerResourcesCpu3000Ram500,
	ContainerResourcesCpu3000Ram1000,
	ContainerResourcesCpu3000Ram2000,
	ContainerResourcesCpu3000Ram3000,
	ContainerResourcesCpu3000Ram4000,
	ContainerResourcesCpu3000Ram5000,
	ContainerResourcesCpu3000Ram6000,
	ContainerResourcesCpu3000Ram7000,
	ContainerResourcesCpu3000Ram8000,
	ContainerResourcesCpu3000Ram9000,
	ContainerResourcesCpu3000Ram10000,
	ContainerResourcesCpu3000Ram11000,
	ContainerResourcesCpu3000Ram12000,
	ContainerResourcesCpu3000Ram13000,
	ContainerResourcesCpu3000Ram14000,
	ContainerResourcesCpu3000Ram15000,
	ContainerResourcesCpu3000Ram16000,
	ContainerResourcesCpu4000Ram500,
	ContainerResourcesCpu4000Ram1000,
	ContainerResourcesCpu4000Ram2000,
	ContainerResourcesCpu4000Ram3000,
	ContainerResourcesCpu4000Ram4000,
	ContainerResourcesCpu4000Ram5000,
	ContainerResourcesCpu4000Ram6000,
	ContainerResourcesCpu4000Ram7000,
	ContainerResourcesCpu4000Ram8000,
	ContainerResourcesCpu4000Ram9000,
	ContainerResourcesCpu4000Ram10000,
	ContainerResourcesCpu4000Ram11000,
	ContainerResourcesCpu4000Ram12000,
	ContainerResourcesCpu4000Ram13000,
	ContainerResourcesCpu4000Ram14000,
	ContainerResourcesCpu4000Ram15000,
	ContainerResourcesCpu4000Ram16000,
}

type EnvironmentVariableInput struct {
	Name   string `json:"name"`
	Value  string `json:"value"`
	Secret bool   `json:"secret"`
	State  State  `json:"state"`
}

// GetName returns EnvironmentVariableInput.Name, and is useful for accessing the field via an interface.
func (v *EnvironmentVariableInput) GetName() string { return v.Name }

// GetValue returns EnvironmentVariableInput.Value, and is useful for accessing the field via an interface.
func (v *EnvironmentVariableInput) GetValue() string { return v.Value }

// GetSecret returns EnvironmentVariableInput.Secret, and is useful for accessing the field via an interface.
func (v *EnvironmentVariableInput) GetSecret() bool { return v.Secret }

// GetState returns EnvironmentVariableInput.State, and is useful for accessing the field via an interface.
func (v *EnvironmentVariableInput) GetState() State { return v.State }

type MountInput struct {
	// Path to mount the volume in the container.
	Path   string           `json:"path"`
	Volume MountVolumeInput `json:"volume"`
	// Set the expected state of this mount.
	// When the state is set to `ABSENT`, the mount will be removed, the volume will be kept.
	State State `json:"state"`
}

// GetPath returns MountInput.Path, and is useful for accessing the field via an interface.
func (v *MountInput) GetPath() string { return v.Path }

// GetVolume returns MountInput.Volume, and is useful for accessing the field via an interface.
func (v *MountInput) GetVolume() MountVolumeInput { return v.Volume }

// GetState returns MountInput.State, and is useful for accessing the field via an interface.
func (v *MountInput) GetState() State { return v.State }

type MountVolumeInput struct {
	// Create the volume if it does not exist.
	AutoCreate bool `json:"autoCreate"`
	// Increase the size of the volume if it already exists.
	Increase bool `json:"increase"`
	// Name of the volume
	Name string `json:"name"`
	// Size of the volume in GB
	Size *int `json:"size"`
}

// GetAutoCreate returns MountVolumeInput.AutoCreate, and is useful for accessing the field via an interface.
func (v *MountVolumeInput) GetAutoCreate() bool { return v.AutoCreate }

// GetIncrease returns MountVolumeInput.Increase, and is useful for accessing the field via an interface.
func (v *MountVolumeInput) GetIncrease() bool { return v.Increase }

// GetName returns MountVolumeInput.Name, and is useful for accessing the field via an interface.
func (v *MountVolumeInput) GetName() string { return v.Name }

// GetSize returns MountVolumeInput.Size, and is useful for accessing the field via an interface.
func (v *MountVolumeInput) GetSize() *int { return v.Size }

type State string

const (
	StatePresent State = "PRESENT"
	StateAbsent  State = "ABSENT"
)

var AllState = []State{
	StatePresent,
	StateAbsent,
}

// __containerJobCreateInput is used internally by genqlient
type __containerJobCreateInput struct {
	ScheduledJob ContainerJobCreateInput `json:"scheduledJob"`
}

// GetScheduledJob returns __containerJobCreateInput.ScheduledJob, and is useful for accessing the field via an interface.
func (v *__containerJobCreateInput) GetScheduledJob() ContainerJobCreateInput { return v.ScheduledJob }

// __containerJobListInput is used internally by genqlient
type __containerJobListInput struct {
	NamespaceName string `json:"namespaceName"`
}

// GetNamespaceName returns __containerJobListInput.NamespaceName, and is useful for accessing the field via an interface.
func (v *__containerJobListInput) GetNamespaceName() string { return v.NamespaceName }

// __containerJobModifyInput is used internally by genqlient
type __containerJobModifyInput struct {
	ScheduledJob ContainerJobModifyInput `json:"scheduledJob"`
}

// GetScheduledJob returns __containerJobModifyInput.ScheduledJob, and is useful for accessing the field via an interface.
func (v *__containerJobModifyInput) GetScheduledJob() ContainerJobModifyInput { return v.ScheduledJob }

// containerJobCreateResponse is returned by containerJobCreate on success.
type containerJobCreateResponse struct {
	ContainerJobCreate ContainerJobResult `json:"containerJobCreate"`
}

// GetContainerJobCreate returns containerJobCreateResponse.ContainerJobCreate, and is useful for accessing the field via an interface.
func (v *containerJobCreateResponse) GetContainerJobCreate() ContainerJobResult {
	return v.ContainerJobCreate
}

// containerJobListNamespace includes the requested fields of the GraphQL type Namespace.
type containerJobListNamespace struct {
	ContainerJobs []containerJobListNamespaceContainerJobsContainerJob `json:"containerJobs"`
}

// GetContainerJobs returns containerJobListNamespace.ContainerJobs, and is useful for accessing the field via an interface.
func (v *containerJobListNamespace) GetContainerJobs() []containerJobListNamespaceContainerJobsContainerJob {
	return v.ContainerJobs
}

// containerJobListNamespaceContainerJobsContainerJob includes the requested fields of the GraphQL type ContainerJob.
type containerJobListNamespaceContainerJobsContainerJob struct {
	ContainerJobResult `json:"-"`
}

// GetName returns containerJobListNamespaceContainerJobsContainerJob.Name, and is useful for accessing the field via an interface.
func (v *containerJobListNamespaceContainerJobsContainerJob) GetName() string {
	return v.ContainerJobResult.Name
}

// GetImage returns containerJobListNamespaceContainerJobsContainerJob.Image, and is useful for accessing the field via an interface.
func (v *containerJobListNamespaceContainerJobsContainerJob) GetImage() string {
	return v.ContainerJobResult.Image
}

// GetEnabled returns containerJobListNamespaceContainerJobsContainerJob.Enabled, and is useful for accessing the field via an interface.
func (v *containerJobListNamespaceContainerJobsContainerJob) GetEnabled() bool {
	return v.ContainerJobResult.Enabled
}

// GetState returns containerJobListNamespaceContainerJobsContainerJob.State, and is useful for accessing the field via an interface.
func (v *containerJobListNamespaceContainerJobsContainerJob) GetState() string {
	return v.ContainerJobResult.State
}

func (v *containerJobListNamespaceContainerJobsContainerJob) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*containerJobListNamespaceContainerJobsContainerJob
		graphql.NoUnmarshalJSON
	}
	firstPass.containerJobListNamespaceContainerJobsContainerJob = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.ContainerJobResult)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalcontainerJobListNamespaceContainerJobsContainerJob struct {
	Name string `json:"name"`

	Image string `json:"image"`

	Enabled bool `json:"enabled"`

	State string `json:"state"`
}

func (v *containerJobListNamespaceContainerJobsContainerJob) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *containerJobListNamespaceContainerJobsContainerJob) __premarshalJSON() (*__premarshalcontainerJobListNamespaceContainerJobsContainerJob, error) {
	var retval __premarshalcontainerJobListNamespaceContainerJobsContainerJob

	retval.Name = v.ContainerJobResult.Name
	retval.Image = v.ContainerJobResult.Image
	retval.Enabled = v.ContainerJobResult.Enabled
	retval.State = v.ContainerJobResult.State
	return &retval, nil
}

// containerJobListResponse is returned by containerJobList on success.
type containerJobListResponse struct {
	Namespace containerJobListNamespace `json:"namespace"`
}

// GetNamespace returns containerJobListResponse.Namespace, and is useful for accessing the field via an interface.
func (v *containerJobListResponse) GetNamespace() containerJobListNamespace { return v.Namespace }

// containerJobModifyResponse is returned by containerJobModify on success.
type containerJobModifyResponse struct {
	ContainerJobModify ContainerJobResult `json:"containerJobModify"`
}

// GetContainerJobModify returns containerJobModifyResponse.ContainerJobModify, and is useful for accessing the field via an interface.
func (v *containerJobModifyResponse) GetContainerJobModify() ContainerJobResult {
	return v.ContainerJobModify
}

// The mutation executed by containerJobCreate.
const containerJobCreate_Operation = `
mutation containerJobCreate ($scheduledJob: ContainerJobCreateInput!) {
	containerJobCreate(scheduledJob: $scheduledJob) {
		... ContainerJobResult
	}
}
fragment ContainerJobResult on ContainerJob {
	name
	image
	enabled
	state
}
`

func containerJobCreate(
	ctx_ context.Context,
	client_ graphql.Client,
	scheduledJob ContainerJobCreateInput,
) (data_ *containerJobCreateResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "containerJobCreate",
		Query:  containerJobCreate_Operation,
		Variables: &__containerJobCreateInput{
			ScheduledJob: scheduledJob,
		},
	}

	data_ = &containerJobCreateResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by containerJobList.
const containerJobList_Operation = `
query containerJobList ($namespaceName: String!) {
	namespace(name: $namespaceName) {
		containerJobs {
			... ContainerJobResult
		}
	}
}
fragment ContainerJobResult on ContainerJob {
	name
	image
	enabled
	state
}
`

func containerJobList(
	ctx_ context.Context,
	client_ graphql.Client,
	namespaceName string,
) (data_ *containerJobListResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "containerJobList",
		Query:  containerJobList_Operation,
		Variables: &__containerJobListInput{
			NamespaceName: namespaceName,
		},
	}

	data_ = &containerJobListResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by containerJobModify.
const containerJobModify_Operation = `
mutation containerJobModify ($scheduledJob: ContainerJobModifyInput!) {
	containerJobModify(scheduledJob: $scheduledJob) {
		... ContainerJobResult
	}
}
fragment ContainerJobResult on ContainerJob {
	name
	image
	enabled
	state
}
`

func containerJobModify(
	ctx_ context.Context,
	client_ graphql.Client,
	scheduledJob ContainerJobModifyInput,
) (data_ *containerJobModifyResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "containerJobModify",
		Query:  containerJobModify_Operation,
		Variables: &__containerJobModifyInput{
			ScheduledJob: scheduledJob,
		},
	}

	data_ = &containerJobModifyResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
